    #"Columnas renombradas" = Table.RenameColumns(#"Encabezados promovidos",{
        {"Age", "Edad"},
        {"Gender", "Genero"},
        {"self_employed", "TrabajadorIndependiente"},
        {"family_history", "HistorialFamiliar"},
        {"treatment", "Tratamiento"},
        {"work_interfere", "InterferenciaTrabajo"},
        {"no_employees", "CantidadEmpleados"},
        {"remote_work", "TrabajoRemoto"},
        {"tech_company", "EmpresaTecnologica"},
        {"benefits", "BeneficiosSaludMental"},
        {"care_options", "OpcionesCuidado"},
        {"wellness_program", "ProgramaBienestar"},
        {"seek_help", "BusquedaAyuda"},
        {"anonymity", "Anonimato"},
        {"leave", "FacilidadLicencia"},
        {"mental_health_consequence", "ConsecuenciaSaludMental"},
        {"phys_health_consequence", "ConsecuenciaSaludFisica"},
        {"coworkers", "CompanerosTrabajo"},
        {"supervisor", "Supervisor"},
        {"mental_health_interview", "EntrevistaSaludMental"},
        {"phys_health_interview", "EntrevistaSaludFisica"},
        {"mental_vs_physical", "MentalVsFisica"},
        {"obs_consequence", "ConsecuenciaObservada"}
    })